import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { configDir } from "../shared/paths.js";

export const SERVICE_LABEL = "com.jiayunxie.aerial";
export const WIN_TASK_NAME = "AerialLocalProxy";

const PLIST_HEADER = "<!-- Generated by aerial; do not edit. Run `aerial service install` to regenerate. -->";
const POSIX_HEADER = "# Generated by aerial; do not edit. Run `aerial service install` to regenerate.";
const DEFAULT_WRAPPER_LOG_MAX_BYTES = 5 * 1024 * 1024;
const DEFAULT_WRAPPER_LOG_BACKUPS = 3;

export function wrapperLogConfig() {
  const out = { maxBytes: DEFAULT_WRAPPER_LOG_MAX_BYTES, backups: DEFAULT_WRAPPER_LOG_BACKUPS };
  const rawMax = process.env.AERIAL_LOG_MAX_BYTES;
  if (rawMax && /^\d+$/.test(String(rawMax).trim())) {
    const n = Number(String(rawMax).trim());
    if (n > 0) out.maxBytes = n;
  }
  const rawBackups = process.env.AERIAL_LOG_BACKUPS;
  if (rawBackups && /^\d+$/.test(String(rawBackups).trim())) {
    const n = Number(String(rawBackups).trim());
    if (n >= 1) out.backups = n;
  }
  return out;
}

export function nodeBinary() {
  return process.env.AERIAL_SERVICE_NODE || process.execPath;
}

export function cliEntry() {
  if (process.env.AERIAL_SERVICE_CLI) return process.env.AERIAL_SERVICE_CLI;
  return path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "cli", "index.js");
}

export function logsDir() {
  return process.env.AERIAL_LOG_DIR || path.join(configDir(), "logs");
}

export function aerialLogPath() {
  return path.join(logsDir(), "aerial.log");
}

export function stdioLogPath() {
  return path.join(logsDir(), "aerial-stdio.log");
}

export function plistPath() {
  return path.join(os.homedir(), "Library", "LaunchAgents", `${SERVICE_LABEL}.plist`);
}

export function darwinWrapperPath() {
  return path.join(configDir(), "bin", "aerial-service.sh");
}

export function winWrapperPath() {
  return path.join(configDir(), "bin", "aerial-service.ps1");
}

function xmlEscape(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function shEscape(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function psEscape(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

export function uidString() {
  if (process.platform !== "darwin") return "";
  const uid = process.getuid?.();
  return uid === undefined || uid === null ? "" : String(uid);
}

export function explicitConfigDir() {
  const v = process.env.AERIAL_CONFIG_DIR;
  return v && v.trim() ? v : undefined;
}

export function renderPlist({ label = SERVICE_LABEL, wrapperPath: wrapper }) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    PLIST_HEADER,
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    "  <key>Label</key>",
    `  <string>${xmlEscape(label)}</string>`,
    "  <key>ProgramArguments</key>",
    "  <array>",
    "    <string>/bin/sh</string>",
    `    <string>${xmlEscape(wrapper)}</string>`,
    "  </array>",
    "  <key>RunAtLoad</key>",
    "  <true/>",
    "  <key>KeepAlive</key>",
    "  <dict>",
    "    <key>SuccessfulExit</key>",
    "    <false/>",
    "    <key>Crashed</key>",
    "    <true/>",
    "  </dict>",
    "  <key>ThrottleInterval</key>",
    "  <integer>10</integer>",
    "</dict>",
    "</plist>",
    ""
  ].join("\n");
}

export function renderDarwinWrapper({ nodePath, cliPath, host, port, stdioLog, aerialLog, configDir: cfg, maxBytes, backups }) {
  const max = Number.isInteger(maxBytes) && maxBytes > 0 ? maxBytes : DEFAULT_WRAPPER_LOG_MAX_BYTES;
  const keep = Number.isInteger(backups) && backups >= 1 ? backups : DEFAULT_WRAPPER_LOG_BACKUPS;
  const lines = [
    "#!/bin/sh",
    POSIX_HEADER,
    "set -e",
    `STDIO_LOG=${shEscape(stdioLog)}`,
    `AERIAL_LOG_FILE=${shEscape(aerialLog)}`,
    `MAX_BYTES=${max}`,
    `BACKUPS=${keep}`,
    `NODE_BIN=${shEscape(nodePath)}`,
    `CLI_ENTRY=${shEscape(cliPath)}`,
    `HOST=${shEscape(host)}`,
    `PORT=${Number(port)}`,
    "STDIO_DIR=$(dirname \"$STDIO_LOG\")",
    "AERIAL_DIR=$(dirname \"$AERIAL_LOG_FILE\")",
    "mkdir -p \"$STDIO_DIR\" \"$AERIAL_DIR\"",
    "if [ -f \"$STDIO_LOG\" ]; then",
    "  SIZE=$(wc -c < \"$STDIO_LOG\" | tr -d ' ')",
    "  if [ \"$SIZE\" -gt \"$MAX_BYTES\" ]; then",
    "    i=$((BACKUPS - 1))",
    "    while [ \"$i\" -ge 1 ]; do",
    "      SRC=\"$STDIO_LOG.$i\"",
    "      DST=\"$STDIO_LOG.$((i + 1))\"",
    "      if [ -f \"$SRC\" ]; then mv \"$SRC\" \"$DST\"; fi",
    "      i=$((i - 1))",
    "    done",
    "    mv \"$STDIO_LOG\" \"$STDIO_LOG.1\"",
    "  fi",
    "fi",
    "export AERIAL_LOG_FILE",
    `export AERIAL_LOG_MAX_BYTES=${max}`,
    `export AERIAL_LOG_BACKUPS=${keep}`
  ];
  if (cfg) lines.push(`export AERIAL_CONFIG_DIR=${shEscape(cfg)}`);
  lines.push("exec \"$NODE_BIN\" \"$CLI_ENTRY\" start --host \"$HOST\" --port \"$PORT\" >> \"$STDIO_LOG\" 2>&1");
  lines.push("");
  return lines.join("\n");
}

export function renderWindowsWrapper({ nodePath, cliPath, host, port, stdioLog, aerialLog, configDir: cfg, maxBytes, backups }) {
  const max = Number.isInteger(maxBytes) && maxBytes > 0 ? maxBytes : DEFAULT_WRAPPER_LOG_MAX_BYTES;
  const keep = Number.isInteger(backups) && backups >= 1 ? backups : DEFAULT_WRAPPER_LOG_BACKUPS;
  const lines = [
    POSIX_HEADER,
    "$ErrorActionPreference = 'Stop'",
    `$node = ${psEscape(nodePath)}`,
    `$cli  = ${psEscape(cliPath)}`,
    `$serviceHost = ${psEscape(host)}`,
    `$servicePort = ${Number(port)}`,
    `$stdioLog = ${psEscape(stdioLog)}`,
    `$aerialLog = ${psEscape(aerialLog)}`,
    `$maxBytes = ${max}`,
    `$backups = ${keep}`,
    "$stdioDir = Split-Path -Parent $stdioLog",
    "$aerialDir = Split-Path -Parent $aerialLog",
    "if (-not (Test-Path -LiteralPath $stdioDir)) { New-Item -ItemType Directory -Path $stdioDir | Out-Null }",
    "if (-not (Test-Path -LiteralPath $aerialDir)) { New-Item -ItemType Directory -Path $aerialDir | Out-Null }",
    "if (Test-Path -LiteralPath $stdioLog) {",
    "  $size = (Get-Item -LiteralPath $stdioLog).Length",
    "  if ($size -gt $maxBytes) {",
    "    for ($i = $backups - 1; $i -ge 1; $i--) {",
    "      $src = \"$stdioLog.$i\"",
    "      $dst = \"$stdioLog.$($i + 1)\"",
    "      if (Test-Path -LiteralPath $src) {",
    "        if (Test-Path -LiteralPath $dst) { Remove-Item -LiteralPath $dst -Force }",
    "        Move-Item -LiteralPath $src -Destination $dst",
    "      }",
    "    }",
    "    if (Test-Path -LiteralPath \"$stdioLog.1\") { Remove-Item -LiteralPath \"$stdioLog.1\" -Force }",
    "    Move-Item -LiteralPath $stdioLog -Destination \"$stdioLog.1\"",
    "  }",
    "}",
    "$env:AERIAL_LOG_FILE = $aerialLog",
    "$env:AERIAL_LOG_MAX_BYTES = \"$maxBytes\"",
    "$env:AERIAL_LOG_BACKUPS = \"$backups\""
  ];
  if (cfg) lines.push(`$env:AERIAL_CONFIG_DIR = ${psEscape(cfg)}`);
  lines.push("& $node $cli start --host $serviceHost --port $servicePort *>> $stdioLog");
  lines.push("");
  return lines.join("\r\n");
}

export function formatSchtasksTR(command) {
  return String(command);
}

export function buildSchtasksCreateArgs({ taskName = WIN_TASK_NAME, wrapperPath: wrapper }) {
  const cmd = `powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File "${wrapper}"`;
  return [
    "/Create",
    "/TN", taskName,
    "/SC", "ONLOGON",
    "/RL", "LIMITED",
    "/F",
    "/TR", formatSchtasksTR(cmd)
  ];
}

export function buildSchtasksArgs(action, taskName = WIN_TASK_NAME) {
  if (action === "delete") return ["/Delete", "/TN", taskName, "/F"];
  if (action === "run") return ["/Run", "/TN", taskName];
  if (action === "end") return ["/End", "/TN", taskName];
  if (action === "query") return ["/Query", "/TN", taskName, "/FO", "LIST"];
  throw new Error(`Unsupported schtasks action: ${action}`);
}
