import test from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import fs from "node:fs";

const temp = fs.mkdtempSync(path.join(os.tmpdir(), "aerial-service-test-"));
process.env.AERIAL_CONFIG_DIR = path.join(temp, "config");
process.env.AERIAL_LOG_DIR = path.join(temp, "logs");
process.env.HOME = temp;
process.env.USERPROFILE = temp;
process.env.AERIAL_API_KEY = "aerial_test_key";
process.env.AERIAL_SKIP_ENV_PERSIST = "1";

const {
  renderPlist,
  renderDarwinWrapper,
  renderWindowsWrapper,
  buildSchtasksCreateArgs,
  serviceInstall,
  serviceStart,
  serviceStop,
  serviceRestart,
  serviceUninstall,
  serviceStatus,
  _internal
} = await import("../src/service/index.js");

function makeRunner() {
  const calls = [];
  const queue = [];
  function run(file, args, opts) {
    calls.push({ file, args, opts });
    const next = queue.shift();
    if (next) return next;
    return { status: 0, stdout: "", stderr: "" };
  }
  run.calls = calls;
  run.queue = queue;
  return run;
}

function absentHealth() {
  return async () => ({ ok: false, error: "ECONNREFUSED" });
}

function aerialHealth() {
  return async () => ({ ok: true, status: 200, body: { ok: true, service: "aerial" } });
}

function nonAerialHealth() {
  return async () => ({ ok: true, status: 200, body: { ok: true, service: "something-else" } });
}

function parseFailHealth() {
  return async () => ({ ok: true, status: 200, parseFailed: true });
}

function healthSequence(...probes) {
  let i = 0;
  return async () => {
    const next = probes[Math.min(i, probes.length - 1)];
    i += 1;
    if (typeof next === "function") return next();
    return next;
  };
}

const ABSENT = { ok: false, error: "ECONNREFUSED" };
const AERIAL = { ok: true, status: 200, body: { ok: true, service: "aerial" } };

function cleanupServiceArtifacts() {
  try {
    const p = _internal.plistPath();
    if (fs.existsSync(p)) fs.unlinkSync(p);
  } catch {}
  try {
    const w = process.platform === "darwin" ? _internal.darwinWrapperPath() : _internal.winWrapperPath();
    if (fs.existsSync(w)) fs.unlinkSync(w);
  } catch {}
}

test("renderPlist embeds generated header, KeepAlive dict, ThrottleInterval=10, and wrapper invocation", () => {
  const plist = renderPlist({ wrapperPath: "/Users/x/Library/Application Support/aerial/bin/aerial-service.sh" });
  assert.match(plist, /<!-- Generated by aerial; do not edit/);
  assert.match(plist, /<key>Label<\/key>\s*<string>com\.jiayunxie\.aerial<\/string>/);
  assert.match(plist, /<key>ThrottleInterval<\/key>\s*<integer>10<\/integer>/);
  assert.match(plist, /<key>KeepAlive<\/key>\s*<dict>[\s\S]*?<key>Crashed<\/key>\s*<true\/>[\s\S]*?<\/dict>/);
  assert.match(plist, /<key>SuccessfulExit<\/key>\s*<false\/>/);
  assert.match(plist, /<string>\/bin\/sh<\/string>/);
  assert.match(plist, /aerial-service\.sh/);
  assert.ok(!/StandardOutPath/.test(plist), "plist must not pin StandardOutPath; wrapper handles stdio redirect");
});

test("renderDarwinWrapper rotates stdio.log, exports log env vars, and exec's node with stdio redirected", () => {
  const wrapper = renderDarwinWrapper({
    nodePath: "/usr/local/bin/node",
    cliPath: "/opt/aerial/src/cli/index.js",
    host: "127.0.0.1",
    port: 18181,
    stdioLog: "/var/log/aerial-stdio.log",
    aerialLog: "/var/log/aerial.log"
  });
  assert.match(wrapper, /^#!\/bin\/sh/);
  assert.match(wrapper, /Generated by aerial/);
  assert.match(wrapper, /STDIO_LOG='\/var\/log\/aerial-stdio\.log'/);
  assert.match(wrapper, /AERIAL_LOG_FILE='\/var\/log\/aerial\.log'/);
  assert.match(wrapper, /MAX_BYTES=5242880/);
  assert.match(wrapper, /BACKUPS=3/);
  assert.match(wrapper, /export AERIAL_LOG_FILE/);
  assert.match(wrapper, /export AERIAL_LOG_MAX_BYTES=5242880/);
  assert.match(wrapper, /export AERIAL_LOG_BACKUPS=3/);
  assert.match(wrapper, /exec "\$NODE_BIN" "\$CLI_ENTRY" start --host "\$HOST" --port "\$PORT" >> "\$STDIO_LOG" 2>&1/);
  assert.ok(!/export AERIAL_CONFIG_DIR/.test(wrapper), "no AERIAL_CONFIG_DIR embed when not explicitly set");
});

test("renderDarwinWrapper conditionally embeds AERIAL_CONFIG_DIR when install-time env had it", () => {
  const wrapper = renderDarwinWrapper({
    nodePath: "/usr/local/bin/node",
    cliPath: "/opt/aerial/src/cli/index.js",
    host: "127.0.0.1",
    port: 18181,
    stdioLog: "/tmp/aerial-stdio.log",
    aerialLog: "/tmp/aerial.log",
    configDir: "/Users/jeremy/custom-config"
  });
  assert.match(wrapper, /export AERIAL_CONFIG_DIR='\/Users\/jeremy\/custom-config'/);
});

test("renderDarwinWrapper shell-escapes paths with single quotes and spaces", () => {
  const wrapper = renderDarwinWrapper({
    nodePath: "/Users/x/My Tools/node",
    cliPath: "/Users/x/aerial 'beta'/src/cli/index.js",
    host: "127.0.0.1",
    port: 18181,
    stdioLog: "/tmp/aerial-stdio.log",
    aerialLog: "/tmp/aerial.log"
  });
  assert.match(wrapper, /NODE_BIN='\/Users\/x\/My Tools\/node'/);
  assert.match(wrapper, /CLI_ENTRY='\/Users\/x\/aerial '\\''beta'\\''\/src\/cli\/index\.js'/);
});

test("service wrapper uses current Node unless AERIAL_SERVICE_NODE explicitly overrides", () => {
  const prev = process.env.AERIAL_SERVICE_NODE;
  try {
    delete process.env.AERIAL_SERVICE_NODE;
    assert.equal(_internal.nodeBinary(), process.execPath);
    process.env.AERIAL_SERVICE_NODE = "/custom/node";
    assert.equal(_internal.nodeBinary(), "/custom/node");
  } finally {
    if (prev === undefined) delete process.env.AERIAL_SERVICE_NODE;
    else process.env.AERIAL_SERVICE_NODE = prev;
  }
});

test("renderWindowsWrapper rotates stdio.log, sets log env vars, and runs node with PowerShell stream redirect", () => {
  const wrapper = renderWindowsWrapper({
    nodePath: "C:\\Program Files\\nodejs\\node.exe",
    cliPath: "C:\\Users\\Jeremy O'Hara\\aerial\\src\\cli.js",
    host: "127.0.0.1",
    port: 18181,
    stdioLog: "C:\\Users\\Jeremy\\AppData\\Roaming\\aerial\\logs\\aerial-stdio.log",
    aerialLog: "C:\\Users\\Jeremy\\AppData\\Roaming\\aerial\\logs\\aerial.log"
  });
  assert.match(wrapper, /\$ErrorActionPreference = 'Stop'/);
  assert.match(wrapper, /\$node = 'C:\\Program Files\\nodejs\\node\.exe'/);
  assert.match(wrapper, /Jeremy O''Hara/);
  assert.match(wrapper, /\$maxBytes = 5242880/);
  assert.match(wrapper, /\$backups = 3/);
  assert.match(wrapper, /\$env:AERIAL_LOG_FILE = \$aerialLog/);
  assert.match(wrapper, /\$env:AERIAL_LOG_MAX_BYTES = "\$maxBytes"/);
  assert.match(wrapper, /& \$node \$cli start --host \$serviceHost --port \$servicePort \*>> \$stdioLog/);
  assert.ok(!/AERIAL_CONFIG_DIR/.test(wrapper), "no AERIAL_CONFIG_DIR embed when not explicitly set");
});

test("renderWindowsWrapper conditionally embeds AERIAL_CONFIG_DIR when install-time env had it", () => {
  const wrapper = renderWindowsWrapper({
    nodePath: "C:\\node.exe",
    cliPath: "C:\\cli.js",
    host: "127.0.0.1",
    port: 18181,
    stdioLog: "C:\\stdio.log",
    aerialLog: "C:\\aerial.log",
    configDir: "C:\\Users\\Jeremy\\custom-aerial"
  });
  assert.match(wrapper, /\$env:AERIAL_CONFIG_DIR = 'C:\\Users\\Jeremy\\custom-aerial'/);
});

test("renderDarwinWrapper propagates install-time AERIAL_LOG_MAX_BYTES / AERIAL_LOG_BACKUPS overrides", () => {
  const wrapper = renderDarwinWrapper({
    nodePath: "/usr/local/bin/node",
    cliPath: "/opt/aerial/src/cli/index.js",
    host: "127.0.0.1",
    port: 18181,
    stdioLog: "/tmp/aerial-stdio.log",
    aerialLog: "/tmp/aerial.log",
    maxBytes: 12345678,
    backups: 7
  });
  assert.match(wrapper, /MAX_BYTES=12345678/);
  assert.match(wrapper, /BACKUPS=7/);
  assert.match(wrapper, /export AERIAL_LOG_MAX_BYTES=12345678/);
  assert.match(wrapper, /export AERIAL_LOG_BACKUPS=7/);
});

test("renderWindowsWrapper propagates install-time AERIAL_LOG_MAX_BYTES / AERIAL_LOG_BACKUPS overrides", () => {
  const wrapper = renderWindowsWrapper({
    nodePath: "C:\\node.exe",
    cliPath: "C:\\cli.js",
    host: "127.0.0.1",
    port: 18181,
    stdioLog: "C:\\stdio.log",
    aerialLog: "C:\\aerial.log",
    maxBytes: 87654321,
    backups: 9
  });
  assert.match(wrapper, /\$maxBytes = 87654321/);
  assert.match(wrapper, /\$backups = 9/);
});

test("buildSchtasksCreateArgs passes /TR without shell-escaped quotes", () => {
  for (const wrapper of [
    "C:\\noSpace\\aerial-service.ps1",
    "C:\\Users\\Jeremy Xie\\AppData\\Roaming\\aerial\\bin\\aerial-service.ps1",
    "C:\\Users\\你好\\aerial\\bin\\aerial-service.ps1"
  ]) {
    const args = buildSchtasksCreateArgs({ wrapperPath: wrapper });
    const trIndex = args.indexOf("/TR");
    assert.ok(trIndex > 0);
    const tr = args[trIndex + 1];
    assert.ok(tr.startsWith("powershell.exe "), `expected /TR to start with powershell.exe but was: ${tr}`);
    assert.ok(!tr.includes('\\"'), `expected /TR to contain real quotes, not backslash-escaped quotes: ${tr}`);
    assert.ok(tr.includes(wrapper));
    assert.ok(tr.includes("-WindowStyle Hidden"));
    assert.ok(tr.includes("-File"));
  }
});

test("buildSchtasksCreateArgs quotes the -File operand separately so Task Scheduler parses paths with spaces", () => {
  const wrapper = "C:\\Users\\Jeremy Xie\\AppData\\Roaming\\aerial\\bin\\aerial-service.ps1";
  const args = buildSchtasksCreateArgs({ wrapperPath: wrapper });
  const tr = args[args.indexOf("/TR") + 1];
  assert.ok(tr.includes(`-File "${wrapper}"`), `expected -File operand wrapped in quotes, but /TR was: ${tr}`);
  assert.ok(!/-File C:\\Users\\Jeremy /.test(tr), "must not register an unquoted path that would be split at the first space");
});

test("serviceInstall throws unsupportedPlatform on linux with actionable message", { skip: process.platform === "darwin" || process.platform === "win32" }, async () => {
  await assert.rejects(async () => serviceInstall({ run: makeRunner(), healthFetch: absentHealth() }), /unsupported platform/);
});

test("serviceInstall on macOS bootstraps via launchctl and writes plist + wrapper", { skip: process.platform !== "darwin" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  run.queue.push({ status: 1, stdout: "", stderr: "Could not find service" });
  run.queue.push({ status: 0, stdout: "", stderr: "" });
  const result = await serviceInstall({ run, healthFetch: healthSequence(ABSENT, AERIAL) });
  assert.equal(result.ok, true);
  assert.equal(result.platform, "darwin");
  assert.ok(fs.existsSync(result.file));
  assert.ok(fs.existsSync(result.wrapper));
  const wrapper = fs.readFileSync(result.wrapper, "utf8");
  assert.match(wrapper, /^#!\/bin\/sh/);
  const plist = fs.readFileSync(result.file, "utf8");
  assert.match(plist, /Generated by aerial/);
  assert.ok(run.calls.find((c) => c.file === "launchctl" && c.args[0] === "bootstrap"));
  assert.equal(result.health?.ok, true, "install must report a health-ok confirmation after bootstrap");
});

test("serviceInstall on Windows runs schtasks /Create followed by /Run and writes wrapper", { skip: process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  run.queue.push({ status: 0, stdout: "", stderr: "" });
  run.queue.push({ status: 0, stdout: "", stderr: "" });
  const result = await serviceInstall({ run, healthFetch: healthSequence(ABSENT, AERIAL) });
  assert.equal(result.ok, true);
  assert.equal(result.platform, "win32");
  assert.ok(fs.existsSync(result.wrapper));
  assert.ok(run.calls.find((c) => c.file === "schtasks.exe" && c.args.includes("/Create")));
  assert.ok(run.calls.find((c) => c.file === "schtasks.exe" && c.args.includes("/Run")));
  assert.equal(result.health?.ok, true, "install must report a health-ok confirmation after /Run");
});

test("serviceInstall surfaces a warning note when GitHub token is missing", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const tokenFile = path.join(process.env.AERIAL_CONFIG_DIR, "github_token");
  if (fs.existsSync(tokenFile)) fs.unlinkSync(tokenFile);
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 1, stdout: "", stderr: "" });
    run.queue.push({ status: 0, stdout: "", stderr: "" });
  } else {
    run.queue.push({ status: 0, stdout: "", stderr: "" });
    run.queue.push({ status: 0, stdout: "", stderr: "" });
  }
  const result = await serviceInstall({ run, healthFetch: healthSequence(ABSENT, AERIAL) });
  assert.equal(result.ok, true);
  assert.ok(result.warning);
  assert.equal(result.warning.code, "github_token_missing");
  assert.match(result.warning.message, /aerial login/);
});

test("serviceInstall detects port conflict (200 but non-Aerial) and exits without writing definition", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  const result = await serviceInstall({ run, healthFetch: nonAerialHealth() });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "port_conflict");
  assert.match(result.message, /not Aerial/);
  assert.equal(run.calls.length, 0, "no service commands should run when port is conflicted");
});

test("serviceInstall detects port conflict via JSON parse failure", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  const result = await serviceInstall({ run, healthFetch: parseFailHealth() });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "port_conflict");
  assert.match(result.message, /Free the port/);
});

test("serviceInstall under foreground Aerial updates definition but does NOT start a second service", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  run.queue.push({ status: 1, stdout: "", stderr: "no such service" });
  if (process.platform === "win32") {
    run.queue.push({ status: 0, stdout: "", stderr: "" });
  }
  const result = await serviceInstall({ run, healthFetch: aerialHealth() });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "foreground_running");
  assert.equal(result.definitionUpdated, true);
  assert.match(result.message, /aerial service start/);
  if (process.platform === "darwin") {
    assert.ok(fs.existsSync(result.file), "plist must be written under foreground_running");
    assert.ok(fs.existsSync(result.wrapper), "wrapper must be written under foreground_running");
    assert.ok(!run.calls.find((c) => c.file === "launchctl" && c.args[0] === "bootstrap"), "must not bootstrap a second service");
  } else {
    assert.ok(fs.existsSync(result.wrapper), "wrapper must be written under foreground_running");
    assert.ok(run.calls.find((c) => c.file === "schtasks.exe" && c.args.includes("/Create")));
    assert.ok(!run.calls.find((c) => c.file === "schtasks.exe" && c.args.includes("/Run")), "must not /Run a second instance");
  }
  cleanupServiceArtifacts();
});

test("serviceInstall on managed+running refreshes definition (does NOT short-circuit) and does NOT start a second service", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  if (process.platform === "darwin") {
    fs.mkdirSync(path.dirname(_internal.plistPath()), { recursive: true });
    fs.writeFileSync(_internal.plistPath(), "<placeholder/>");
    fs.mkdirSync(path.dirname(_internal.darwinWrapperPath()), { recursive: true });
    fs.writeFileSync(_internal.darwinWrapperPath(), "#!/bin/sh\n# placeholder\n");
  } else {
    fs.mkdirSync(path.dirname(_internal.winWrapperPath()), { recursive: true });
    fs.writeFileSync(_internal.winWrapperPath(), "rem placeholder");
  }
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 0, stdout: "{\n\t\"PID\" = 1234;\n};", stderr: "" });
  } else {
    run.queue.push({ status: 0, stdout: "TaskName: \\AerialLocalProxy\r\nStatus: Running", stderr: "" });
    run.queue.push({ status: 0, stdout: "", stderr: "" });
  }
  const result = await serviceInstall({ run, healthFetch: aerialHealth() });
  assert.equal(result.ok, true);
  assert.equal(result.definitionUpdated, true);
  assert.match(result.note, /definition refreshed/);
  assert.match(result.note, /aerial service restart/);
  if (process.platform === "darwin") {
    const plist = fs.readFileSync(_internal.plistPath(), "utf8");
    const wrapper = fs.readFileSync(_internal.darwinWrapperPath(), "utf8");
    assert.match(plist, /Generated by aerial/, "plist must be rewritten with real content, not preserved as placeholder");
    assert.match(wrapper, /^#!\/bin\/sh/);
    assert.match(wrapper, /Generated by aerial/, "wrapper must be rewritten, not left as placeholder");
    assert.ok(!run.calls.find((c) => c.file === "launchctl" && c.args[0] === "bootstrap"), "must not bootstrap a second service");
  } else {
    const wrapper = fs.readFileSync(_internal.winWrapperPath(), "utf8");
    assert.match(wrapper, /Generated by aerial/, "wrapper must be rewritten, not left as placeholder");
    assert.ok(run.calls.find((c) => c.file === "schtasks.exe" && c.args.includes("/Create")), "must regenerate via schtasks /Create");
    assert.ok(!run.calls.find((c) => c.file === "schtasks.exe" && c.args.includes("/Run")), "must not /Run a second instance");
  }
  cleanupServiceArtifacts();
});

test("serviceInstall on managed+running surfaces ok:false with managed_definition_refresh_failed when /Create fails (Windows)", { skip: process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  fs.mkdirSync(path.dirname(_internal.winWrapperPath()), { recursive: true });
  fs.writeFileSync(_internal.winWrapperPath(), "rem placeholder");
  const run = makeRunner();
  run.queue.push({ status: 0, stdout: "TaskName: \\AerialLocalProxy\r\nStatus: Running", stderr: "" });
  run.queue.push({ status: 9, stdout: "", stderr: "ERROR: Access is denied." });
  const result = await serviceInstall({ run, healthFetch: aerialHealth() });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "managed_definition_refresh_failed");
  assert.match(result.message, /Resolve the underlying schtasks error/);
  cleanupServiceArtifacts();
});

test("serviceInstall on foreground+running surfaces ok:false with foreground_definition_refresh_failed when /Create fails (Windows)", { skip: process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  run.queue.push({ status: 1, stdout: "", stderr: "no such service" });
  run.queue.push({ status: 9, stdout: "", stderr: "ERROR: Access is denied." });
  const result = await serviceInstall({ run, healthFetch: aerialHealth() });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "foreground_definition_refresh_failed");
  assert.equal(result.definitionUpdated, false);
  assert.match(result.message, /wrapper was rewritten but schtasks \/Create failed/);
  assert.match(result.message, /Resolve the underlying schtasks error/);
  assert.equal(result.create.status, 9);
  assert.match(result.create.stderr, /Access is denied/);
  assert.ok(fs.existsSync(result.wrapper), "wrapper must still be on disk after /Create failure (atomicWriteText runs first)");
  assert.ok(run.calls.find((c) => c.file === "schtasks.exe" && c.args.includes("/Create")), "/Create must be attempted under foreground_aerial");
  assert.ok(!run.calls.find((c) => c.file === "schtasks.exe" && c.args.includes("/Run")), "/Run must NOT be attempted when definition refresh failed");
  cleanupServiceArtifacts();
});

test("serviceInstall returns health_check_failed when bootstrap succeeds but /health never becomes Aerial (darwin)", { skip: process.platform !== "darwin" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  run.queue.push({ status: 1, stdout: "", stderr: "Could not find service" });
  run.queue.push({ status: 0, stdout: "", stderr: "" });
  const result = await serviceInstall({ run, healthFetch: absentHealth(), healthDeadlineMs: 50 });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "health_check_failed");
  assert.equal(result.definitionWritten, true);
  assert.equal(result.startAttempted, true);
  assert.match(result.message, /health did not become Aerial/);
  assert.ok(result.diagnostics, "must include diagnostics");
  assert.equal(typeof result.diagnostics.stdioLog, "string");
  assert.equal(typeof result.diagnostics.aerialLog, "string");
  assert.ok(Number.isInteger(result.diagnostics.health.attempts));
  assert.ok(result.diagnostics.health.attempts >= 1);
  assert.ok(fs.existsSync(result.file), "plist still written on health_check_failed");
  assert.ok(fs.existsSync(result.wrapper), "wrapper still written on health_check_failed");
  cleanupServiceArtifacts();
});

test("serviceInstall returns health_check_failed when /Run succeeds but /health never becomes Aerial (windows)", { skip: process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  run.queue.push({ status: 0, stdout: "", stderr: "" });
  run.queue.push({ status: 0, stdout: "", stderr: "" });
  const result = await serviceInstall({ run, healthFetch: absentHealth(), healthDeadlineMs: 50 });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "health_check_failed");
  assert.equal(result.definitionWritten, true);
  assert.equal(result.startAttempted, true);
  assert.match(result.message, /health did not become Aerial/);
  assert.ok(result.diagnostics);
  assert.equal(typeof result.diagnostics.stdioLog, "string");
  assert.ok(fs.existsSync(result.wrapper), "wrapper still written on health_check_failed");
  cleanupServiceArtifacts();
});

test("serviceInstall diagnostics report wrapper node path when wrapper was just written", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 1, stdout: "", stderr: "" });
    run.queue.push({ status: 0, stdout: "", stderr: "" });
  } else {
    run.queue.push({ status: 0, stdout: "", stderr: "" });
    run.queue.push({ status: 0, stdout: "", stderr: "" });
  }
  const result = await serviceInstall({ run, healthFetch: absentHealth(), healthDeadlineMs: 50 });
  assert.equal(result.reason, "health_check_failed");
  assert.equal(typeof result.diagnostics.wrapperNode, "string", "wrapper node path must be parsed from wrapper");
  assert.ok(result.diagnostics.wrapperNode.length > 0);
  cleanupServiceArtifacts();
});

test("serviceInstall surfaces port_conflict when after-start probe shows non-Aerial 200", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 1, stdout: "", stderr: "" });
    run.queue.push({ status: 0, stdout: "", stderr: "" });
  } else {
    run.queue.push({ status: 0, stdout: "", stderr: "" });
    run.queue.push({ status: 0, stdout: "", stderr: "" });
  }
  const result = await serviceInstall({ run, healthFetch: healthSequence(ABSENT, { ok: true, status: 200, body: { service: "not-aerial" } }), healthDeadlineMs: 50 });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "port_conflict");
  assert.match(result.message, /non-Aerial/);
  cleanupServiceArtifacts();
});

test("serviceStart returns health_check_failed when trigger succeeds but /health stays absent", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  if (process.platform === "darwin") {
    fs.mkdirSync(path.dirname(_internal.plistPath()), { recursive: true });
    fs.writeFileSync(_internal.plistPath(), "<placeholder/>");
    fs.mkdirSync(path.dirname(_internal.darwinWrapperPath()), { recursive: true });
    fs.writeFileSync(_internal.darwinWrapperPath(), "#!/bin/sh\nNODE_BIN='/missing/node'\n");
  } else {
    fs.mkdirSync(path.dirname(_internal.winWrapperPath()), { recursive: true });
    fs.writeFileSync(_internal.winWrapperPath(), "$node = 'C:\\missing\\node.exe'\n");
  }
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 1, stdout: "", stderr: "Could not find service" });
    run.queue.push({ status: 0, stdout: "", stderr: "" });
  } else {
    run.queue.push({ status: 0, stdout: "TaskName: \\AerialLocalProxy\r\nStatus: Ready", stderr: "" });
    run.queue.push({ status: 0, stdout: "", stderr: "" });
  }
  const result = await serviceStart({ run, healthFetch: absentHealth(), healthDeadlineMs: 50 });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "health_check_failed");
  assert.equal(result.startAttempted, true);
  assert.ok(result.diagnostics);
  assert.equal(typeof result.diagnostics.stdioLog, "string");
  assert.equal(typeof result.diagnostics.wrapperNode, "string");
  cleanupServiceArtifacts();
});

test("tokenWarning explains env-only AERIAL_GITHUB_TOKEN is not inherited by the service", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const tokenFile = path.join(process.env.AERIAL_CONFIG_DIR, "github_token");
  if (fs.existsSync(tokenFile)) fs.unlinkSync(tokenFile);
  const prev = process.env.AERIAL_GITHUB_TOKEN;
  process.env.AERIAL_GITHUB_TOKEN = "ghp_env_only";
  try {
    const run = makeRunner();
    if (process.platform === "darwin") {
      run.queue.push({ status: 1, stdout: "", stderr: "" });
      run.queue.push({ status: 0, stdout: "", stderr: "" });
    } else {
      run.queue.push({ status: 0, stdout: "", stderr: "" });
      run.queue.push({ status: 0, stdout: "", stderr: "" });
    }
    const result = await serviceInstall({ run, healthFetch: healthSequence(ABSENT, AERIAL) });
    assert.ok(result.warning, "env-only token still warrants a warning because service does not inherit env");
    assert.equal(result.warning.code, "github_token_missing");
    assert.match(result.warning.message, /AERIAL_GITHUB_TOKEN/);
    assert.match(result.warning.message, /background service does not inherit/);
    assert.match(result.warning.message, /aerial login/);
  } finally {
    if (prev === undefined) delete process.env.AERIAL_GITHUB_TOKEN;
    else process.env.AERIAL_GITHUB_TOKEN = prev;
    cleanupServiceArtifacts();
  }
});

test("serviceStart rejects when service is not installed", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  if (process.platform === "win32") run.queue.push({ status: 1, stdout: "", stderr: "" });
  const result = await serviceStart({ run, healthFetch: absentHealth() });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "not_installed");
  assert.match(result.message, /service install/);
});

test("serviceStart returns ok=false with port_conflict when something non-Aerial is on the port", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  if (process.platform === "darwin") {
    fs.mkdirSync(path.dirname(_internal.plistPath()), { recursive: true });
    fs.writeFileSync(_internal.plistPath(), "<placeholder/>");
  }
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 1, stdout: "", stderr: "Could not find service" });
  } else {
    run.queue.push({ status: 0, stdout: "TaskName: \\AerialLocalProxy\r\nStatus: Ready", stderr: "" });
  }
  const result = await serviceStart({ run, healthFetch: nonAerialHealth() });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "port_conflict");
  cleanupServiceArtifacts();
});

test("serviceStop is idempotent (exit 0 + note) when service is not installed", { skip: process.platform !== "darwin" && process.platform !== "win32" }, () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  if (process.platform === "win32") run.queue.push({ status: 1, stdout: "", stderr: "" });
  const result = serviceStop({ run });
  assert.equal(result.ok, true);
  assert.equal(result.note, "not installed");
});

test("serviceStop is idempotent (exit 0 + note) when service is installed but not running", { skip: process.platform !== "darwin" && process.platform !== "win32" }, () => {
  cleanupServiceArtifacts();
  if (process.platform === "darwin") {
    fs.mkdirSync(path.dirname(_internal.plistPath()), { recursive: true });
    fs.writeFileSync(_internal.plistPath(), "<placeholder/>");
  }
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 1, stdout: "", stderr: "Could not find service" });
  } else {
    run.queue.push({ status: 0, stdout: "TaskName: \\AerialLocalProxy\r\nStatus: Ready", stderr: "" });
  }
  const result = serviceStop({ run });
  assert.equal(result.ok, true);
  assert.equal(result.note, "not running");
  cleanupServiceArtifacts();
});

test("serviceStop on macOS uses launchctl bootout (not kill SIGTERM)", { skip: process.platform !== "darwin" }, () => {
  fs.mkdirSync(path.dirname(_internal.plistPath()), { recursive: true });
  fs.writeFileSync(_internal.plistPath(), "<placeholder/>");
  const run = makeRunner();
  run.queue.push({ status: 0, stdout: "{\n\t\"PID\" = 1234;\n};", stderr: "" });
  run.queue.push({ status: 0, stdout: "", stderr: "" });
  const result = serviceStop({ run });
  assert.equal(result.ok, true);
  const bootoutCall = run.calls.find((c) => c.file === "launchctl" && c.args[0] === "bootout");
  assert.ok(bootoutCall, "expected launchctl bootout to be invoked");
  assert.ok(!run.calls.find((c) => c.file === "launchctl" && c.args[0] === "kill"));
  cleanupServiceArtifacts();
});

test("serviceRestart blocks start when stop fails", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  if (process.platform === "darwin") {
    fs.mkdirSync(path.dirname(_internal.plistPath()), { recursive: true });
    fs.writeFileSync(_internal.plistPath(), "<placeholder/>");
  }
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 0, stdout: "{\n\t\"PID\" = 1234;\n};", stderr: "" });
    run.queue.push({ status: 1, stdout: "", stderr: "bootout refused" });
  } else {
    run.queue.push({ status: 0, stdout: "TaskName: \\AerialLocalProxy\r\nStatus: Running", stderr: "" });
    run.queue.push({ status: 1, stdout: "", stderr: "/End failed" });
  }
  const result = await serviceRestart({ run, healthFetch: absentHealth() });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "stop_failed");
  assert.ok(!result.start, "start must not be attempted when stop failed");
  cleanupServiceArtifacts();
});

test("serviceUninstall does best-effort stop on Windows before /Delete", { skip: process.platform !== "win32" }, () => {
  fs.mkdirSync(path.dirname(_internal.winWrapperPath()), { recursive: true });
  fs.writeFileSync(_internal.winWrapperPath(), "rem placeholder");
  const run = makeRunner();
  run.queue.push({ status: 0, stdout: "TaskName: \\AerialLocalProxy\r\nStatus: Running", stderr: "" });
  run.queue.push({ status: 0, stdout: "", stderr: "" });
  run.queue.push({ status: 0, stdout: "", stderr: "" });
  const result = serviceUninstall({ run });
  assert.equal(result.ok, true);
  const endIdx = run.calls.findIndex((c) => c.file === "schtasks.exe" && c.args.includes("/End"));
  const delIdx = run.calls.findIndex((c) => c.file === "schtasks.exe" && c.args.includes("/Delete"));
  assert.ok(endIdx >= 0, "expected /End to be called");
  assert.ok(delIdx > endIdx, "expected /Delete to follow /End");
  cleanupServiceArtifacts();
});

test("serviceUninstall on darwin returns ok:false with bootout_failed when launchctl bootout fails", { skip: process.platform !== "darwin" }, () => {
  cleanupServiceArtifacts();
  fs.mkdirSync(path.dirname(_internal.plistPath()), { recursive: true });
  fs.writeFileSync(_internal.plistPath(), "<placeholder/>");
  fs.mkdirSync(path.dirname(_internal.darwinWrapperPath()), { recursive: true });
  fs.writeFileSync(_internal.darwinWrapperPath(), "#!/bin/sh\n# placeholder\n");
  const run = makeRunner();
  run.queue.push({ status: 0, stdout: "{\n\t\"PID\" = 1234;\n};", stderr: "" });
  run.queue.push({ status: 9216, stdout: "", stderr: "Boot-out failed: 5: Input/output error" });
  const result = serviceUninstall({ run });
  assert.equal(result.ok, false);
  assert.equal(result.reason, "bootout_failed");
  assert.ok(fs.existsSync(_internal.plistPath()), "plist must be preserved when bootout fails");
  assert.ok(fs.existsSync(_internal.darwinWrapperPath()), "wrapper must be preserved when bootout fails");
  assert.match(result.message, /Retry/);
  assert.match(result.bootout.stderr, /Boot-out failed/);
  cleanupServiceArtifacts();
});

test("serviceUninstall on darwin succeeds and removes plist+wrapper when bootout succeeds", { skip: process.platform !== "darwin" }, () => {
  cleanupServiceArtifacts();
  fs.mkdirSync(path.dirname(_internal.plistPath()), { recursive: true });
  fs.writeFileSync(_internal.plistPath(), "<placeholder/>");
  fs.mkdirSync(path.dirname(_internal.darwinWrapperPath()), { recursive: true });
  fs.writeFileSync(_internal.darwinWrapperPath(), "#!/bin/sh\n# placeholder\n");
  const run = makeRunner();
  run.queue.push({ status: 0, stdout: "{\n\t\"PID\" = 1234;\n};", stderr: "" });
  run.queue.push({ status: 0, stdout: "", stderr: "" });
  const result = serviceUninstall({ run });
  assert.equal(result.ok, true);
  assert.ok(!fs.existsSync(_internal.plistPath()), "plist must be removed on success");
  assert.ok(!fs.existsSync(_internal.darwinWrapperPath()), "wrapper must be removed on success");
  cleanupServiceArtifacts();
});

test("serviceUninstall is idempotent (exit 0 + note) when not installed", { skip: process.platform !== "darwin" && process.platform !== "win32" }, () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  if (process.platform === "win32") run.queue.push({ status: 1, stdout: "", stderr: "" });
  const result = serviceUninstall({ run });
  assert.equal(result.ok, true);
  assert.equal(result.note, "no service installed");
});

test("serviceStatus aggregates service + health + logs + auth and distinguishes summary states", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 1, stdout: "", stderr: "Could not find service" });
  } else {
    run.queue.push({ status: 1, stdout: "", stderr: "" });
  }
  const status = await serviceStatus({ run, healthFetch: absentHealth() });
  assert.equal(status.schema, "aerial.service-status.v1");
  assert.equal(status.supported, true);
  assert.equal(status.service.installed, false);
  assert.equal(status.summary, "not installed");
  assert.equal(typeof status.auth.api_key.state, "string");
  assert.equal(typeof status.auth.github_token.state, "string");
});

test("serviceStatus marks running (foreground) when health is Aerial but service not loaded", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 1, stdout: "", stderr: "Could not find service" });
  } else {
    run.queue.push({ status: 1, stdout: "", stderr: "" });
  }
  const status = await serviceStatus({ run, healthFetch: aerialHealth() });
  assert.equal(status.summary, "running (foreground)");
  assert.equal(status.health.aerial, true);
  assert.equal(status.health.supervisor, "foreground");
});

test("serviceStatus marks port conflict in health block when non-Aerial 200 on port", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 1, stdout: "", stderr: "Could not find service" });
  } else {
    run.queue.push({ status: 1, stdout: "", stderr: "" });
  }
  const status = await serviceStatus({ run, healthFetch: nonAerialHealth() });
  assert.equal(status.health.portConflict, true);
  assert.equal(status.summary, "port conflict (non-Aerial process on port)");
});

test("serviceStatus on linux marks supported=false and returns schema-valid result", { skip: process.platform === "darwin" || process.platform === "win32" }, async () => {
  const run = makeRunner();
  const status = await serviceStatus({ run, healthFetch: absentHealth() });
  assert.equal(status.schema, "aerial.service-status.v1");
  assert.equal(status.supported, false);
  assert.equal(status.service.reason, "unsupported_platform");
  assert.equal(status.service.wrapper.stale, false);
  assert.deepEqual(status.service.wrapper.staleReasons, []);
  assert.equal(run.calls.length, 0);
});

test("authBlock reports tri-state (present|missing|invalid) for api_key and github_token", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const apiKey = path.join(process.env.AERIAL_CONFIG_DIR, "api_key");
  const token = path.join(process.env.AERIAL_CONFIG_DIR, "github_token");
  fs.mkdirSync(process.env.AERIAL_CONFIG_DIR, { recursive: true });
  fs.writeFileSync(apiKey, "aerial_xxx");
  if (fs.existsSync(token)) fs.unlinkSync(token);
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 1, stdout: "", stderr: "" });
  } else {
    run.queue.push({ status: 1, stdout: "", stderr: "" });
  }
  const status = await serviceStatus({ run, healthFetch: absentHealth() });
  assert.equal(status.auth.api_key.state, "present");
  assert.equal(status.auth.github_token.state, "missing");
});

test("authBlock classifies an existing empty credential file as `invalid` (not `missing`) to match docs/usage.md", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const apiKey = path.join(process.env.AERIAL_CONFIG_DIR, "api_key");
  const token = path.join(process.env.AERIAL_CONFIG_DIR, "github_token");
  fs.mkdirSync(process.env.AERIAL_CONFIG_DIR, { recursive: true });
  fs.writeFileSync(apiKey, "");
  fs.writeFileSync(token, "   \n  ");
  const run = makeRunner();
  run.queue.push({ status: 1, stdout: "", stderr: "" });
  const status = await serviceStatus({ run, healthFetch: absentHealth() });
  assert.equal(status.auth.api_key.state, "invalid");
  assert.equal(status.auth.api_key.reason, "empty");
  assert.equal(status.auth.github_token.state, "invalid");
  assert.equal(status.auth.github_token.reason, "empty");
});

test("serviceStatus logs block reflects install-time AERIAL_LOG_MAX_BYTES / AERIAL_LOG_BACKUPS overrides", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const prevMax = process.env.AERIAL_LOG_MAX_BYTES;
  const prevBackups = process.env.AERIAL_LOG_BACKUPS;
  process.env.AERIAL_LOG_MAX_BYTES = "20971520";
  process.env.AERIAL_LOG_BACKUPS = "5";
  try {
    const run = makeRunner();
    run.queue.push({ status: 1, stdout: "", stderr: "" });
    const status = await serviceStatus({ run, healthFetch: absentHealth() });
    assert.equal(status.logs.maxFileBytes, 20971520);
    assert.equal(status.logs.rotateKeep, 5);
    assert.equal(status.logs.source, "next-install-default", "no installed wrapper present, must report the env-derived next-install default");
  } finally {
    if (prevMax === undefined) delete process.env.AERIAL_LOG_MAX_BYTES;
    else process.env.AERIAL_LOG_MAX_BYTES = prevMax;
    if (prevBackups === undefined) delete process.env.AERIAL_LOG_BACKUPS;
    else process.env.AERIAL_LOG_BACKUPS = prevBackups;
  }
});

test("serviceStatus logs block parses the installed wrapper when present and labels source=installed-wrapper", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const prevMax = process.env.AERIAL_LOG_MAX_BYTES;
  const prevBackups = process.env.AERIAL_LOG_BACKUPS;
  process.env.AERIAL_LOG_MAX_BYTES = "1";
  process.env.AERIAL_LOG_BACKUPS = "1";
  try {
    if (process.platform === "darwin") {
      const wrapper = _internal.darwinWrapperPath();
      fs.mkdirSync(path.dirname(wrapper), { recursive: true });
      const content = renderDarwinWrapper({
        nodePath: "/usr/local/bin/node",
        cliPath: "/opt/aerial/src/cli/index.js",
        host: "127.0.0.1",
        port: 18181,
        stdioLog: "/tmp/aerial-stdio.log",
        aerialLog: "/tmp/aerial.log",
        maxBytes: 33554432,
        backups: 8
      });
      fs.writeFileSync(wrapper, content);
    } else {
      const wrapper = _internal.winWrapperPath();
      fs.mkdirSync(path.dirname(wrapper), { recursive: true });
      const content = renderWindowsWrapper({
        nodePath: "C:\\node.exe",
        cliPath: "C:\\cli.js",
        host: "127.0.0.1",
        port: 18181,
        stdioLog: "C:\\stdio.log",
        aerialLog: "C:\\aerial.log",
        maxBytes: 33554432,
        backups: 8
      });
      fs.writeFileSync(wrapper, content);
    }
    const run = makeRunner();
    run.queue.push({ status: 1, stdout: "", stderr: "" });
    const status = await serviceStatus({ run, healthFetch: absentHealth() });
    assert.equal(status.logs.maxFileBytes, 33554432, "must reflect installed-wrapper value, not current env");
    assert.equal(status.logs.rotateKeep, 8, "must reflect installed-wrapper value, not current env");
    assert.equal(status.logs.source, "installed-wrapper");
  } finally {
    if (prevMax === undefined) delete process.env.AERIAL_LOG_MAX_BYTES;
    else process.env.AERIAL_LOG_MAX_BYTES = prevMax;
    if (prevBackups === undefined) delete process.env.AERIAL_LOG_BACKUPS;
    else process.env.AERIAL_LOG_BACKUPS = prevBackups;
    cleanupServiceArtifacts();
  }
});

test("parseWrapperLogValues returns null on missing/garbled wrapper and parsed values on valid wrappers", () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "aerial-wrapper-parse-"));
  const sh = path.join(tmp, "aerial-service.sh");
  const ps1 = path.join(tmp, "aerial-service.ps1");
  assert.equal(_internal.parseWrapperLogValues(sh), null, "missing file returns null");
  fs.writeFileSync(sh, "#!/bin/sh\nMAX_BYTES=99999\nBACKUPS=4\nexec node");
  assert.deepEqual(_internal.parseWrapperLogValues(sh), { maxBytes: 99999, backups: 4 });
  fs.writeFileSync(ps1, "$ErrorActionPreference='Stop'\n$maxBytes = 7777\n$backups = 9\n& node");
  assert.deepEqual(_internal.parseWrapperLogValues(ps1), { maxBytes: 7777, backups: 9 });
  fs.writeFileSync(sh, "#!/bin/sh\nMAX_BYTES=notanumber\nBACKUPS=4");
  assert.equal(_internal.parseWrapperLogValues(sh), null, "non-numeric values return null");
});

function writeInstalledArtifacts({ nodePath, cliPath, maxBytes = 4194304, backups = 5, omitWrapper = false, garbledLogConfig = false } = {}) {
  if (process.platform === "darwin") {
    fs.mkdirSync(path.dirname(_internal.plistPath()), { recursive: true });
    fs.writeFileSync(_internal.plistPath(), "<placeholder/>");
    if (!omitWrapper) {
      const wf = _internal.darwinWrapperPath();
      fs.mkdirSync(path.dirname(wf), { recursive: true });
      if (garbledLogConfig) {
        fs.writeFileSync(wf, `#!/bin/sh\nNODE_BIN='${nodePath}'\nCLI_ENTRY='${cliPath}'\nMAX_BYTES=notanumber\nBACKUPS=4\nexec node\n`);
      } else {
        fs.writeFileSync(wf, renderDarwinWrapper({ nodePath, cliPath, host: "127.0.0.1", port: 18181, stdioLog: "/tmp/x.log", aerialLog: "/tmp/y.log", maxBytes, backups }));
      }
    }
  } else if (process.platform === "win32") {
    if (!omitWrapper) {
      const wf = _internal.winWrapperPath();
      fs.mkdirSync(path.dirname(wf), { recursive: true });
      if (garbledLogConfig) {
        fs.writeFileSync(wf, `$ErrorActionPreference='Stop'\n$node = '${nodePath}'\n$cli  = '${cliPath}'\n$maxBytes = notanumber\n$backups = 4\n& node\n`);
      } else {
        fs.writeFileSync(wf, renderWindowsWrapper({ nodePath, cliPath, host: "127.0.0.1", port: 18181, stdioLog: "C:\\tmp\\x.log", aerialLog: "C:\\tmp\\y.log", maxBytes, backups }));
      }
    }
  }
}

function installedQueryRun() {
  const run = makeRunner();
  if (process.platform === "darwin") {
    run.queue.push({ status: 1, stdout: "", stderr: "" });
  } else if (process.platform === "win32") {
    run.queue.push({ status: 0, stdout: "TaskName: \\AerialLocalProxy\r\nStatus: Ready", stderr: "" });
  }
  return run;
}

test("serviceStatus wrapper block: not installed -> stale=false, staleReasons=[]", async () => {
  cleanupServiceArtifacts();
  const run = makeRunner();
  if (process.platform === "darwin") run.queue.push({ status: 1, stdout: "", stderr: "Could not find" });
  else if (process.platform === "win32") run.queue.push({ status: 1, stdout: "", stderr: "" });
  const s = await serviceStatus({ run, healthFetch: absentHealth() });
  assert.equal(s.service.installed, false);
  assert.deepEqual(s.service.wrapper.staleReasons, []);
  assert.equal(s.service.wrapper.stale, false);
});

test("serviceStatus wrapper block: installed but wrapper file missing -> wrapper_missing", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  writeInstalledArtifacts({ nodePath: process.execPath, cliPath: "/tmp/cli.js", omitWrapper: true });
  const s = await serviceStatus({ run: installedQueryRun(), healthFetch: absentHealth() });
  assert.equal(s.service.installed, true);
  assert.equal(s.service.wrapper.stale, true);
  assert.deepEqual(s.service.wrapper.staleReasons, ["wrapper_missing"]);
  assert.equal(s.service.wrapper.nodeExists, undefined);
  assert.equal(s.service.wrapper.cliExists, undefined);
  cleanupServiceArtifacts();
});

test("serviceStatus wrapper block: wrapper node path missing -> wrapper_node_missing", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const missingNode = process.platform === "win32" ? "C:\\nope\\node.exe" : "/nope/node";
  writeInstalledArtifacts({ nodePath: missingNode, cliPath: process.execPath });
  const s = await serviceStatus({ run: installedQueryRun(), healthFetch: absentHealth() });
  assert.equal(s.service.wrapper.nodeExists, false);
  assert.equal(s.service.wrapper.cliExists, true);
  assert.equal(s.service.wrapper.stale, true);
  assert.ok(s.service.wrapper.staleReasons.includes("wrapper_node_missing"));
  assert.ok(!s.service.wrapper.staleReasons.includes("wrapper_cli_missing"));
  cleanupServiceArtifacts();
});

test("serviceStatus wrapper block: wrapper cli path missing -> wrapper_cli_missing", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const missingCli = process.platform === "win32" ? "C:\\nope\\cli.js" : "/nope/cli.js";
  writeInstalledArtifacts({ nodePath: process.execPath, cliPath: missingCli });
  const s = await serviceStatus({ run: installedQueryRun(), healthFetch: absentHealth() });
  assert.equal(s.service.wrapper.nodeExists, true);
  assert.equal(s.service.wrapper.cliExists, false);
  assert.equal(s.service.wrapper.stale, true);
  assert.ok(s.service.wrapper.staleReasons.includes("wrapper_cli_missing"));
  cleanupServiceArtifacts();
});

test("serviceStatus wrapper block: unparseable log config -> wrapper_log_config_unparseable", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  writeInstalledArtifacts({ nodePath: process.execPath, cliPath: process.execPath, garbledLogConfig: true });
  const s = await serviceStatus({ run: installedQueryRun(), healthFetch: absentHealth() });
  assert.equal(s.service.wrapper.logConfigParseable, false);
  assert.ok(s.service.wrapper.staleReasons.includes("wrapper_log_config_unparseable"));
  cleanupServiceArtifacts();
});

test("serviceStatus wrapper block: existsSync only, no executable bit assumption on Windows", { skip: process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const fake = path.join(temp, "fake-node-no-x.exe");
  fs.writeFileSync(fake, "");
  writeInstalledArtifacts({ nodePath: fake, cliPath: process.execPath });
  const s = await serviceStatus({ run: installedQueryRun(), healthFetch: absentHealth() });
  assert.equal(s.service.wrapper.nodeExists, true, "Windows: fs.existsSync must say true regardless of executable bit");
  assert.ok(!s.service.wrapper.staleReasons.includes("wrapper_node_missing"));
  cleanupServiceArtifacts();
});

test("serviceStatus wrapper block: fully healthy installed wrapper -> stale=false", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  writeInstalledArtifacts({ nodePath: process.execPath, cliPath: process.execPath });
  const s = await serviceStatus({ run: installedQueryRun(), healthFetch: absentHealth() });
  assert.equal(s.service.installed, true);
  assert.equal(s.service.wrapper.stale, false);
  assert.deepEqual(s.service.wrapper.staleReasons, []);
  assert.equal(s.service.wrapper.nodeExists, true);
  assert.equal(s.service.wrapper.cliExists, true);
  assert.equal(s.service.wrapper.logConfigParseable, true);
  cleanupServiceArtifacts();
});

test("parseWrapperPaths round-trips single-quote and space in node/cli paths", { skip: process.platform !== "darwin" && process.platform !== "win32" }, async () => {
  cleanupServiceArtifacts();
  const tricky = path.join(temp, "O'Connor dir");
  fs.mkdirSync(tricky, { recursive: true });
  const trickyNode = path.join(tricky, process.platform === "win32" ? "node.exe" : "node");
  const trickyCli = path.join(tricky, "cli.js");
  fs.writeFileSync(trickyNode, "");
  fs.writeFileSync(trickyCli, "");
  writeInstalledArtifacts({ nodePath: trickyNode, cliPath: trickyCli });
  const wrapperFile = process.platform === "darwin" ? _internal.darwinWrapperPath() : _internal.winWrapperPath();
  const parsed = _internal.parseWrapperPaths(wrapperFile);
  assert.equal(parsed.node, trickyNode, "node path must round-trip through escaped wrapper");
  assert.equal(parsed.cli, trickyCli, "cli path must round-trip through escaped wrapper");
  const s = await serviceStatus({ run: installedQueryRun(), healthFetch: absentHealth() });
  assert.equal(s.service.wrapper.nodeExists, true, "wrapper with quoted path must not falsely report node missing");
  assert.equal(s.service.wrapper.cliExists, true, "wrapper with quoted path must not falsely report cli missing");
  assert.deepEqual(s.service.wrapper.staleReasons, []);
  cleanupServiceArtifacts();
});
