import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { configDir, apiKeyPath, githubTokenPath } from "./paths.js";
import { loadConfig } from "./config.js";
import { logEvent } from "./log.js";

const SERVICE_LABEL = "com.jiayunxie.aerial";
const WIN_TASK_NAME = "AerialLocalProxy";
const PLIST_HEADER = "<!-- Generated by aerial; do not edit. Run `aerial service install` to regenerate. -->";
const POSIX_HEADER = "# Generated by aerial; do not edit. Run `aerial service install` to regenerate.";
const DEFAULT_WRAPPER_LOG_MAX_BYTES = 5 * 1024 * 1024;
const DEFAULT_WRAPPER_LOG_BACKUPS = 3;
const HEALTH_TIMEOUT_MS = 1500;
const HEALTH_START_TIMEOUT_MS = 5000;

function wrapperLogConfig() {
  const out = { maxBytes: DEFAULT_WRAPPER_LOG_MAX_BYTES, backups: DEFAULT_WRAPPER_LOG_BACKUPS };
  const rawMax = process.env.AERIAL_LOG_MAX_BYTES;
  if (rawMax && /^\d+$/.test(String(rawMax).trim())) {
    const n = Number(String(rawMax).trim());
    if (n > 0) out.maxBytes = n;
  }
  const rawBackups = process.env.AERIAL_LOG_BACKUPS;
  if (rawBackups && /^\d+$/.test(String(rawBackups).trim())) {
    const n = Number(String(rawBackups).trim());
    if (n >= 1) out.backups = n;
  }
  return out;
}

function defaultRunCommand(file, args, opts = {}) {
  if (process.env.AERIAL_SERVICE_DRYRUN === "1") {
    const installed = process.env.AERIAL_SERVICE_DRYRUN_INSTALLED === "1";
    const fail = process.env.AERIAL_SERVICE_DRYRUN_FAIL || "";
    if (file === "schtasks.exe" && Array.isArray(args)) {
      if (args.includes("/Query")) {
        if (installed) {
          return { status: 0, signal: undefined, stdout: "TaskName: \\AerialLocalProxy\r\nStatus: Running", stderr: "", error: undefined, dryRun: true };
        }
        return { status: 1, signal: undefined, stdout: "", stderr: "(dryrun) task not registered", error: undefined, dryRun: true };
      }
      if (args.includes("/Delete") && fail === "delete") {
        return { status: 9, signal: undefined, stdout: "", stderr: "ERROR: Access is denied.", error: undefined, dryRun: true };
      }
    }
    if (file === "launchctl" && Array.isArray(args)) {
      if (args[0] === "list") {
        if (installed) {
          return { status: 0, signal: undefined, stdout: '{\n\t"PID" = 1234;\n\t"LastExitStatus" = 0;\n};', stderr: "", error: undefined, dryRun: true };
        }
        return { status: 1, signal: undefined, stdout: "", stderr: "(dryrun) service not loaded", error: undefined, dryRun: true };
      }
      if (args[0] === "bootout" && fail === "bootout") {
        return { status: 9216, signal: undefined, stdout: "", stderr: "Boot-out failed: 5: Input/output error", error: undefined, dryRun: true };
      }
    }
    return { status: 0, signal: undefined, stdout: "", stderr: "", error: undefined, dryRun: true };
  }
  const res = spawnSync(file, args, {
    stdio: opts.stdio || "pipe",
    encoding: "utf8",
    timeout: opts.timeout || 15000,
    env: opts.env || process.env,
    windowsHide: true
  });
  return {
    status: res.status,
    signal: res.signal,
    stdout: res.stdout || "",
    stderr: res.stderr || "",
    error: res.error
  };
}

function nodeBinary() {
  return process.env.AERIAL_SERVICE_NODE || process.execPath;
}

function cliEntry() {
  if (process.env.AERIAL_SERVICE_CLI) return process.env.AERIAL_SERVICE_CLI;
  return path.join(path.dirname(fileURLToPath(import.meta.url)), "cli.js");
}

function logsDir() {
  return process.env.AERIAL_LOG_DIR || path.join(configDir(), "logs");
}

function aerialLogPath() {
  return path.join(logsDir(), "aerial.log");
}

function stdioLogPath() {
  return path.join(logsDir(), "aerial-stdio.log");
}

function plistPath() {
  return path.join(os.homedir(), "Library", "LaunchAgents", `${SERVICE_LABEL}.plist`);
}

function darwinWrapperPath() {
  return path.join(configDir(), "bin", "aerial-service.sh");
}

function winWrapperPath() {
  return path.join(configDir(), "bin", "aerial-service.ps1");
}

function ensureDir(file) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
}

function atomicWriteText(file, content, { mode } = {}) {
  ensureDir(file);
  const tmp = `${file}.aerial-svc-tmp-${process.pid}-${Math.random().toString(36).slice(2)}`;
  const opts = mode !== undefined ? { mode } : undefined;
  fs.writeFileSync(tmp, content, opts);
  try {
    if (process.platform === "win32" && fs.existsSync(file)) fs.unlinkSync(file);
    fs.renameSync(tmp, file);
  } catch (err) {
    try { fs.unlinkSync(tmp); } catch {}
    throw err;
  }
  if (process.platform !== "win32" && mode !== undefined) {
    try { fs.chmodSync(file, mode); } catch {}
  }
}

function xmlEscape(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function shEscape(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function psEscape(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function uidString() {
  if (process.platform !== "darwin") return "";
  const uid = process.getuid?.();
  return uid === undefined || uid === null ? "" : String(uid);
}

function explicitConfigDir() {
  const v = process.env.AERIAL_CONFIG_DIR;
  return v && v.trim() ? v : undefined;
}

export function renderPlist({ label = SERVICE_LABEL, wrapperPath: wrapper }) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    PLIST_HEADER,
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    "  <key>Label</key>",
    `  <string>${xmlEscape(label)}</string>`,
    "  <key>ProgramArguments</key>",
    "  <array>",
    "    <string>/bin/sh</string>",
    `    <string>${xmlEscape(wrapper)}</string>`,
    "  </array>",
    "  <key>RunAtLoad</key>",
    "  <true/>",
    "  <key>KeepAlive</key>",
    "  <dict>",
    "    <key>SuccessfulExit</key>",
    "    <false/>",
    "    <key>Crashed</key>",
    "    <true/>",
    "  </dict>",
    "  <key>ThrottleInterval</key>",
    "  <integer>10</integer>",
    "</dict>",
    "</plist>",
    ""
  ].join("\n");
}

export function renderDarwinWrapper({ nodePath, cliPath, host, port, stdioLog, aerialLog, configDir: cfg, maxBytes, backups }) {
  const max = Number.isInteger(maxBytes) && maxBytes > 0 ? maxBytes : DEFAULT_WRAPPER_LOG_MAX_BYTES;
  const keep = Number.isInteger(backups) && backups >= 1 ? backups : DEFAULT_WRAPPER_LOG_BACKUPS;
  const lines = [
    "#!/bin/sh",
    POSIX_HEADER,
    "set -e",
    `STDIO_LOG=${shEscape(stdioLog)}`,
    `AERIAL_LOG_FILE=${shEscape(aerialLog)}`,
    `MAX_BYTES=${max}`,
    `BACKUPS=${keep}`,
    `NODE_BIN=${shEscape(nodePath)}`,
    `CLI_ENTRY=${shEscape(cliPath)}`,
    `HOST=${shEscape(host)}`,
    `PORT=${Number(port)}`,
    "STDIO_DIR=$(dirname \"$STDIO_LOG\")",
    "AERIAL_DIR=$(dirname \"$AERIAL_LOG_FILE\")",
    "mkdir -p \"$STDIO_DIR\" \"$AERIAL_DIR\"",
    "if [ -f \"$STDIO_LOG\" ]; then",
    "  SIZE=$(wc -c < \"$STDIO_LOG\" | tr -d ' ')",
    "  if [ \"$SIZE\" -gt \"$MAX_BYTES\" ]; then",
    "    i=$((BACKUPS - 1))",
    "    while [ \"$i\" -ge 1 ]; do",
    "      SRC=\"$STDIO_LOG.$i\"",
    "      DST=\"$STDIO_LOG.$((i + 1))\"",
    "      if [ -f \"$SRC\" ]; then mv \"$SRC\" \"$DST\"; fi",
    "      i=$((i - 1))",
    "    done",
    "    mv \"$STDIO_LOG\" \"$STDIO_LOG.1\"",
    "  fi",
    "fi",
    "export AERIAL_LOG_FILE",
    `export AERIAL_LOG_MAX_BYTES=${max}`,
    `export AERIAL_LOG_BACKUPS=${keep}`
  ];
  if (cfg) lines.push(`export AERIAL_CONFIG_DIR=${shEscape(cfg)}`);
  lines.push("exec \"$NODE_BIN\" \"$CLI_ENTRY\" start --host \"$HOST\" --port \"$PORT\" >> \"$STDIO_LOG\" 2>&1");
  lines.push("");
  return lines.join("\n");
}

export function renderWindowsWrapper({ nodePath, cliPath, host, port, stdioLog, aerialLog, configDir: cfg, maxBytes, backups }) {
  const max = Number.isInteger(maxBytes) && maxBytes > 0 ? maxBytes : DEFAULT_WRAPPER_LOG_MAX_BYTES;
  const keep = Number.isInteger(backups) && backups >= 1 ? backups : DEFAULT_WRAPPER_LOG_BACKUPS;
  const lines = [
    POSIX_HEADER,
    "$ErrorActionPreference = 'Stop'",
    `$node = ${psEscape(nodePath)}`,
    `$cli  = ${psEscape(cliPath)}`,
    `$serviceHost = ${psEscape(host)}`,
    `$servicePort = ${Number(port)}`,
    `$stdioLog = ${psEscape(stdioLog)}`,
    `$aerialLog = ${psEscape(aerialLog)}`,
    `$maxBytes = ${max}`,
    `$backups = ${keep}`,
    "$stdioDir = Split-Path -Parent $stdioLog",
    "$aerialDir = Split-Path -Parent $aerialLog",
    "if (-not (Test-Path -LiteralPath $stdioDir)) { New-Item -ItemType Directory -Path $stdioDir | Out-Null }",
    "if (-not (Test-Path -LiteralPath $aerialDir)) { New-Item -ItemType Directory -Path $aerialDir | Out-Null }",
    "if (Test-Path -LiteralPath $stdioLog) {",
    "  $size = (Get-Item -LiteralPath $stdioLog).Length",
    "  if ($size -gt $maxBytes) {",
    "    for ($i = $backups - 1; $i -ge 1; $i--) {",
    "      $src = \"$stdioLog.$i\"",
    "      $dst = \"$stdioLog.$($i + 1)\"",
    "      if (Test-Path -LiteralPath $src) {",
    "        if (Test-Path -LiteralPath $dst) { Remove-Item -LiteralPath $dst -Force }",
    "        Move-Item -LiteralPath $src -Destination $dst",
    "      }",
    "    }",
    "    if (Test-Path -LiteralPath \"$stdioLog.1\") { Remove-Item -LiteralPath \"$stdioLog.1\" -Force }",
    "    Move-Item -LiteralPath $stdioLog -Destination \"$stdioLog.1\"",
    "  }",
    "}",
    "$env:AERIAL_LOG_FILE = $aerialLog",
    "$env:AERIAL_LOG_MAX_BYTES = \"$maxBytes\"",
    "$env:AERIAL_LOG_BACKUPS = \"$backups\""
  ];
  if (cfg) lines.push(`$env:AERIAL_CONFIG_DIR = ${psEscape(cfg)}`);
  lines.push("& $node $cli start --host $serviceHost --port $servicePort *>> $stdioLog");
  lines.push("");
  return lines.join("\r\n");
}

function quoteSchtasksTR(command) {
  const wrapped = command.replace(/"/g, '\\"');
  return `\\"${wrapped}\\"`;
}

export function buildSchtasksCreateArgs({ taskName = WIN_TASK_NAME, wrapperPath: wrapper }) {
  const cmd = `powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File "${wrapper}"`;
  return [
    "/Create",
    "/TN", taskName,
    "/SC", "ONLOGON",
    "/RL", "LIMITED",
    "/F",
    "/TR", quoteSchtasksTR(cmd)
  ];
}

function buildSchtasksArgs(action, taskName = WIN_TASK_NAME) {
  if (action === "delete") return ["/Delete", "/TN", taskName, "/F"];
  if (action === "run") return ["/Run", "/TN", taskName];
  if (action === "end") return ["/End", "/TN", taskName];
  if (action === "query") return ["/Query", "/TN", taskName, "/FO", "LIST"];
  throw new Error(`Unsupported schtasks action: ${action}`);
}

function isUnsupportedPlatform() {
  return process.platform !== "darwin" && process.platform !== "win32";
}

function unsupportedError(action) {
  const platform = process.platform;
  return new Error(`aerial service ${action}: unsupported platform (${platform}). Service management is implemented for macOS (launchd) and Windows (Task Scheduler). On ${platform}, run \`aerial start\` directly or wrap it in your own init system.`);
}

async function defaultHealthFetch(host, port) {
  if (process.env.AERIAL_SERVICE_DRYRUN === "1") {
    return { ok: false, error: "dryrun" };
  }
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), HEALTH_TIMEOUT_MS);
  try {
    const res = await fetch(`http://${host}:${port}/health`, { signal: controller.signal });
    let body;
    let parseFailed = false;
    try {
      body = await res.json();
    } catch {
      parseFailed = true;
    }
    return { ok: res.ok, status: res.status, body, parseFailed };
  } catch (err) {
    return { ok: false, error: err.message };
  } finally {
    clearTimeout(timer);
  }
}

function classifyHealth(probe) {
  if (!probe || probe.error) return { mode: "absent" };
  if (probe.status !== 200) return { mode: "absent", httpStatus: probe.status };
  if (probe.parseFailed) return { mode: "port_conflict", reason: "health body is not JSON" };
  if (!probe.body || probe.body.service !== "aerial") {
    return { mode: "port_conflict", reason: "200 response but not Aerial" };
  }
  return { mode: "aerial_running", body: probe.body };
}

function authFileStatus(file) {
  if (!fs.existsSync(file)) return { file, state: "missing" };
  try {
    const data = fs.readFileSync(file, "utf8");
    if (!data || !data.trim()) return { file, state: "invalid", reason: "empty" };
    return { file, state: "present" };
  } catch (err) {
    return { file, state: "invalid", reason: err.message };
  }
}

function authBlock() {
  return {
    api_key: authFileStatus(apiKeyPath()),
    github_token: authFileStatus(githubTokenPath())
  };
}

function statFile(file) {
  if (!file) return { exists: false };
  try {
    if (!fs.existsSync(file)) return { exists: false };
    return { exists: true, size: fs.statSync(file).size };
  } catch {
    return { exists: false };
  }
}

function logsBlock() {
  const dir = logsDir();
  const primary = aerialLogPath();
  const stdio = stdioLogPath();
  let wrapperFile;
  if (process.platform === "darwin") wrapperFile = darwinWrapperPath();
  else if (process.platform === "win32") wrapperFile = winWrapperPath();
  const parsed = wrapperFile ? parseWrapperLogValues(wrapperFile) : null;
  let maxBytes;
  let rotateKeep;
  let source;
  if (parsed) {
    maxBytes = parsed.maxBytes;
    rotateKeep = parsed.backups;
    source = "installed-wrapper";
  } else {
    const cfg = wrapperLogConfig();
    maxBytes = cfg.maxBytes;
    rotateKeep = cfg.backups;
    source = "next-install-default";
  }
  return {
    dir,
    primary: { file: primary, ...statFile(primary) },
    stdio: { file: stdio, ...statFile(stdio) },
    maxFileBytes: maxBytes,
    rotateKeep,
    source
  };
}

function parseWrapperLogValues(file) {
  if (!file) return null;
  try {
    if (!fs.existsSync(file)) return null;
    const data = fs.readFileSync(file, "utf8");
    let maxBytes;
    let backups;
    if (file.endsWith(".sh")) {
      const m = data.match(/^MAX_BYTES=(\d+)\s*$/m);
      const b = data.match(/^BACKUPS=(\d+)\s*$/m);
      if (m) maxBytes = Number(m[1]);
      if (b) backups = Number(b[1]);
    } else if (file.endsWith(".ps1")) {
      const m = data.match(/^\$maxBytes\s*=\s*(\d+)\s*$/m);
      const b = data.match(/^\$backups\s*=\s*(\d+)\s*$/m);
      if (m) maxBytes = Number(m[1]);
      if (b) backups = Number(b[1]);
    }
    if (!Number.isInteger(maxBytes) || maxBytes <= 0) return null;
    if (!Number.isInteger(backups) || backups < 1) return null;
    return { maxBytes, backups };
  } catch {
    return null;
  }
}

function darwinServiceState(ctx) {
  const r = ctx.run("launchctl", ["list", SERVICE_LABEL]);
  const installed = fs.existsSync(plistPath());
  if (!installed) return { installed: false, loaded: false };
  if (r.status !== 0) return { installed: true, loaded: false };
  const pidMatch = /"PID"\s*=\s*(\d+)/.exec(r.stdout);
  const lastExitMatch = /"LastExitStatus"\s*=\s*(-?\d+)/.exec(r.stdout);
  return {
    installed: true,
    loaded: true,
    pid: pidMatch ? Number(pidMatch[1]) : undefined,
    lastExitStatus: lastExitMatch ? Number(lastExitMatch[1]) : undefined
  };
}

function windowsServiceState(ctx) {
  const r = ctx.run("schtasks.exe", buildSchtasksArgs("query"));
  if (r.status !== 0) return { installed: false, loaded: false };
  const statusMatch = /Status:\s*(\S+)/i.exec(r.stdout);
  const status = statusMatch ? statusMatch[1].trim() : undefined;
  return { installed: true, loaded: status === "Running", status };
}

function serviceState(ctx) {
  if (process.platform === "darwin") return darwinServiceState(ctx);
  if (process.platform === "win32") return windowsServiceState(ctx);
  return { installed: false, loaded: false, reason: "unsupported_platform" };
}

function tokenWarning() {
  const tokenFile = githubTokenPath();
  if (fs.existsSync(tokenFile)) {
    try {
      const data = fs.readFileSync(tokenFile, "utf8");
      if (data && data.trim()) return undefined;
    } catch {}
  }
  return {
    level: "warning",
    code: "github_token_missing",
    message: "GitHub token is not configured. Service will start, but proxy requests return 503 until you run `aerial login`."
  };
}

function darwinWriteDefinition() {
  const wrapper = darwinWrapperPath();
  const config = loadConfig();
  const logCfg = wrapperLogConfig();
  const wrapperContent = renderDarwinWrapper({
    nodePath: nodeBinary(),
    cliPath: cliEntry(),
    host: config.host,
    port: config.port,
    stdioLog: stdioLogPath(),
    aerialLog: aerialLogPath(),
    configDir: explicitConfigDir(),
    maxBytes: logCfg.maxBytes,
    backups: logCfg.backups
  });
  atomicWriteText(wrapper, wrapperContent, { mode: 0o755 });
  const file = plistPath();
  const plistContent = renderPlist({ wrapperPath: wrapper });
  atomicWriteText(file, plistContent, { mode: 0o644 });
  return { file, wrapper };
}

function darwinBootstrap(ctx) {
  const file = plistPath();
  const existing = ctx.run("launchctl", ["list", SERVICE_LABEL]);
  if (existing.status === 0) {
    ctx.run("launchctl", ["bootout", `gui/${uidString()}`, file], { stdio: "ignore" });
  }
  return ctx.run("launchctl", ["bootstrap", `gui/${uidString()}`, file]);
}

function darwinBootout(ctx) {
  const file = plistPath();
  return ctx.run("launchctl", ["bootout", `gui/${uidString()}`, file]);
}

function windowsWriteDefinition(ctx) {
  const wrapper = winWrapperPath();
  const config = loadConfig();
  const logCfg = wrapperLogConfig();
  const wrapperContent = renderWindowsWrapper({
    nodePath: nodeBinary(),
    cliPath: cliEntry(),
    host: config.host,
    port: config.port,
    stdioLog: stdioLogPath(),
    aerialLog: aerialLogPath(),
    configDir: explicitConfigDir(),
    maxBytes: logCfg.maxBytes,
    backups: logCfg.backups
  });
  atomicWriteText(wrapper, wrapperContent);
  const args = buildSchtasksCreateArgs({ wrapperPath: wrapper });
  const create = ctx.run("schtasks.exe", args);
  return { wrapper, create };
}

async function describeRunning(ctx, host, port, healthFetch) {
  const probe = await (healthFetch || defaultHealthFetch)(host, port);
  const cls = classifyHealth(probe);
  if (cls.mode !== "aerial_running") return { cls, probe };
  const state = serviceState(ctx);
  const supervisor = state.installed && state.loaded ? "service-managed" : "foreground";
  return { cls, probe, supervisor };
}

export async function serviceInstall({ run = defaultRunCommand, healthFetch } = {}) {
  if (isUnsupportedPlatform()) throw unsupportedError("install");
  const ctx = { run };
  const config = loadConfig();
  const { cls, supervisor } = await describeRunning(ctx, config.host, config.port, healthFetch);
  if (cls.mode === "port_conflict") {
    logEvent("service_install", { platform: process.platform, ok: false, reason: "port_conflict" });
    return {
      ok: false,
      action: "install",
      platform: process.platform,
      reason: "port_conflict",
      message: `Port ${config.port} is already in use by a non-Aerial process: ${cls.reason}. Free the port and rerun.`
    };
  }
  if (cls.mode === "aerial_running" && supervisor === "service-managed") {
    let writeInfo;
    if (process.platform === "darwin") {
      const written = darwinWriteDefinition();
      writeInfo = { file: written.file, wrapper: written.wrapper, label: SERVICE_LABEL };
    } else {
      const written = windowsWriteDefinition(ctx);
      writeInfo = { taskName: WIN_TASK_NAME, wrapper: written.wrapper, create: { status: written.create.status, stderr: written.create.stderr } };
      if (written.create.status !== 0) {
        logEvent("service_install", { platform: "win32", ok: false, reason: "managed_definition_refresh_failed", status: written.create.status });
        return {
          ok: false,
          action: "install",
          platform: "win32",
          reason: "managed_definition_refresh_failed",
          message: `schtasks /Create failed (status ${written.create.status}) while refreshing the managed-service definition. The running service was not disturbed, but wrapper/env changes were NOT applied. Resolve the underlying schtasks error and rerun \`aerial service install\`.`,
          warning: tokenWarning(),
          ...writeInfo
        };
      }
    }
    logEvent("service_install", { platform: process.platform, ok: true, note: "managed_refreshed", definitionUpdated: true });
    return {
      ok: true,
      action: "install",
      platform: process.platform,
      note: "already running (service-managed); definition refreshed; run `aerial service restart` to apply wrapper/env changes",
      definitionUpdated: true,
      warning: tokenWarning(),
      ...writeInfo
    };
  }
  if (cls.mode === "aerial_running" && supervisor === "foreground") {
    let writeInfo;
    if (process.platform === "darwin") {
      const written = darwinWriteDefinition();
      writeInfo = { file: written.file, wrapper: written.wrapper, label: SERVICE_LABEL };
    } else {
      const written = windowsWriteDefinition(ctx);
      writeInfo = { taskName: WIN_TASK_NAME, wrapper: written.wrapper, create: { status: written.create.status, stderr: written.create.stderr } };
      if (written.create.status !== 0) {
        logEvent("service_install", { platform: "win32", ok: false, reason: "foreground_definition_refresh_failed", status: written.create.status });
        return {
          ok: false,
          action: "install",
          platform: "win32",
          reason: "foreground_definition_refresh_failed",
          definitionUpdated: false,
          message: `Aerial is already running in the foreground on port ${config.port}. The wrapper was rewritten but schtasks /Create failed (status ${written.create.status}), so the Task Scheduler definition was NOT refreshed. Resolve the underlying schtasks error and rerun \`aerial service install\`.`,
          warning: tokenWarning(),
          ...writeInfo
        };
      }
    }
    logEvent("service_install", { platform: process.platform, ok: false, reason: "foreground_running", definitionUpdated: true });
    return {
      ok: false,
      action: "install",
      platform: process.platform,
      reason: "foreground_running",
      definitionUpdated: true,
      message: `Aerial is already running in the foreground on port ${config.port}. The service definition has been updated, but the service was NOT started to avoid running two instances. Next step: stop the foreground process, then run \`aerial service start\`.`,
      warning: tokenWarning(),
      ...writeInfo
    };
  }
  let result;
  if (process.platform === "darwin") {
    const written = darwinWriteDefinition();
    const bootstrap = darwinBootstrap(ctx);
    const ok = bootstrap.status === 0;
    result = { ok, action: "install", platform: "darwin", file: written.file, wrapper: written.wrapper, label: SERVICE_LABEL, bootstrap: { status: bootstrap.status, stderr: bootstrap.stderr } };
    if (!ok) result.reason = "bootstrap_failed";
  } else {
    const written = windowsWriteDefinition(ctx);
    const createOk = written.create.status === 0;
    if (!createOk) {
      result = { ok: false, action: "install", platform: "win32", taskName: WIN_TASK_NAME, wrapper: written.wrapper, create: { status: written.create.status, stderr: written.create.stderr }, reason: "create_failed" };
    } else {
      const runRes = ctx.run("schtasks.exe", buildSchtasksArgs("run"));
      const ok = runRes.status === 0;
      result = { ok, action: "install", platform: "win32", taskName: WIN_TASK_NAME, wrapper: written.wrapper, create: { status: written.create.status, stderr: written.create.stderr }, run: { status: runRes.status, stderr: runRes.stderr } };
      if (!ok) result.reason = "run_failed";
    }
  }
  result.warning = tokenWarning();
  logEvent("service_install", { platform: process.platform, ok: result.ok });
  return result;
}

export async function serviceStart({ run = defaultRunCommand, healthFetch } = {}) {
  if (isUnsupportedPlatform()) throw unsupportedError("start");
  const ctx = { run };
  const config = loadConfig();
  const state = serviceState(ctx);
  if (!state.installed) {
    return {
      ok: false,
      action: "start",
      platform: process.platform,
      reason: "not_installed",
      message: "Service is not installed. Run `aerial service install` first."
    };
  }
  const { cls, supervisor } = await describeRunning(ctx, config.host, config.port, healthFetch);
  if (cls.mode === "port_conflict") {
    return {
      ok: false,
      action: "start",
      platform: process.platform,
      reason: "port_conflict",
      message: `Port ${config.port} is already in use by a non-Aerial process: ${cls.reason}. Free the port and rerun.`
    };
  }
  if (cls.mode === "aerial_running" && supervisor === "foreground") {
    return {
      ok: false,
      action: "start",
      platform: process.platform,
      reason: "foreground_running",
      message: `Aerial is already running in the foreground on port ${config.port}. Stop the foreground process before starting the service.`
    };
  }
  if (cls.mode === "aerial_running" && supervisor === "service-managed") {
    return {
      ok: true,
      action: "start",
      platform: process.platform,
      note: "already running (service-managed)",
      warning: tokenWarning()
    };
  }
  let r;
  if (process.platform === "darwin") {
    r = darwinBootstrap(ctx);
  } else {
    r = ctx.run("schtasks.exe", buildSchtasksArgs("run"));
  }
  const ok = r.status === 0;
  logEvent("service_start", { platform: process.platform, status: r.status });
  return {
    ok,
    action: "start",
    platform: process.platform,
    status: r.status,
    stderr: r.stderr,
    warning: tokenWarning(),
    ...(ok ? {} : { reason: process.platform === "darwin" ? "bootstrap_failed" : "run_failed" })
  };
}

export function serviceStop({ run = defaultRunCommand } = {}) {
  if (isUnsupportedPlatform()) throw unsupportedError("stop");
  const ctx = { run };
  const state = serviceState(ctx);
  if (!state.installed) {
    return { ok: true, action: "stop", platform: process.platform, note: "not installed" };
  }
  if (!state.loaded) {
    return { ok: true, action: "stop", platform: process.platform, note: "not running" };
  }
  let r;
  if (process.platform === "darwin") {
    r = darwinBootout(ctx);
  } else {
    r = ctx.run("schtasks.exe", buildSchtasksArgs("end"));
  }
  logEvent("service_stop", { platform: process.platform, status: r.status });
  return { ok: r.status === 0, action: "stop", platform: process.platform, status: r.status, stderr: r.stderr };
}

export async function serviceRestart(opts = {}) {
  const stop = serviceStop(opts);
  if (!stop.ok) {
    return { ok: false, action: "restart", platform: process.platform, stop, reason: "stop_failed" };
  }
  const start = await serviceStart(opts);
  return { ok: start.ok, action: "restart", platform: process.platform, stop, start, warning: start.warning };
}

export function serviceUninstall({ run = defaultRunCommand } = {}) {
  if (isUnsupportedPlatform()) throw unsupportedError("uninstall");
  const ctx = { run };
  const state = serviceState(ctx);
  if (!state.installed) {
    return { ok: true, action: "uninstall", platform: process.platform, note: "no service installed" };
  }
  if (process.platform === "darwin") {
    const file = plistPath();
    const wrapper = darwinWrapperPath();
    if (state.loaded) {
      const bootout = darwinBootout(ctx);
      if (bootout.status !== 0) {
        logEvent("service_uninstall", { platform: "darwin", ok: false, reason: "bootout_failed", status: bootout.status });
        return {
          ok: false,
          action: "uninstall",
          platform: "darwin",
          reason: "bootout_failed",
          file,
          wrapper,
          bootout: { status: bootout.status, stderr: bootout.stderr },
          message: `launchctl bootout failed (status ${bootout.status}). Service is still loaded; plist and wrapper were preserved. Retry with \`aerial service uninstall\`.`
        };
      }
      try { fs.unlinkSync(file); } catch {}
      if (fs.existsSync(wrapper)) {
        try { fs.unlinkSync(wrapper); } catch {}
      }
      logEvent("service_uninstall", { platform: "darwin", ok: true });
      return { ok: true, action: "uninstall", platform: "darwin", file, wrapper, bootout: { status: bootout.status, stderr: bootout.stderr } };
    }
    try { fs.unlinkSync(file); } catch {}
    if (fs.existsSync(wrapper)) {
      try { fs.unlinkSync(wrapper); } catch {}
    }
    logEvent("service_uninstall", { platform: "darwin", ok: true });
    return { ok: true, action: "uninstall", platform: "darwin", file, wrapper, bootout: { status: 0, skipped: "not_loaded" } };
  }
  if (state.loaded) {
    ctx.run("schtasks.exe", buildSchtasksArgs("end"));
  }
  const del = ctx.run("schtasks.exe", buildSchtasksArgs("delete"));
  const wrapper = winWrapperPath();
  let wrapperRemoved = false;
  if (del.status === 0 && fs.existsSync(wrapper)) {
    try { fs.unlinkSync(wrapper); wrapperRemoved = true; } catch {}
  }
  logEvent("service_uninstall", { platform: "win32", ok: del.status === 0 });
  return {
    ok: del.status === 0,
    action: "uninstall",
    platform: "win32",
    taskName: WIN_TASK_NAME,
    wrapper,
    wrapperRemoved,
    delete: { status: del.status, stderr: del.stderr },
    ...(del.status === 0 ? {} : { reason: "delete_failed", message: `schtasks /Delete failed (status ${del.status}). Task and wrapper were preserved. Retry with \`aerial service uninstall\`.` })
  };
}

export async function serviceStatus({ run = defaultRunCommand, healthFetch } = {}) {
  const config = loadConfig();
  const ctx = { run };
  if (isUnsupportedPlatform()) {
    return {
      schema: "aerial.service-status.v1",
      platform: process.platform,
      supported: false,
      config: { host: config.host, port: config.port },
      service: { installed: false, loaded: false, reason: "unsupported_platform", platform: process.platform },
      health: { ok: false, error: "unsupported_platform" },
      logs: logsBlock(),
      auth: authBlock(),
      summary: "unsupported"
    };
  }
  const state = serviceState(ctx);
  const probe = await (healthFetch || defaultHealthFetch)(config.host, config.port);
  const cls = classifyHealth(probe);
  let supervisor;
  if (cls.mode === "aerial_running") {
    supervisor = state.installed && state.loaded ? "service-managed" : "foreground";
  }
  const health = { ...probe };
  if (cls.mode === "port_conflict") {
    health.portConflict = true;
    health.conflictReason = cls.reason;
  }
  if (cls.mode === "aerial_running") {
    health.aerial = true;
    health.supervisor = supervisor;
  }
  let summary;
  if (cls.mode === "aerial_running" && supervisor === "service-managed") summary = "running (service-managed)";
  else if (cls.mode === "aerial_running" && supervisor === "foreground") summary = "running (foreground)";
  else if (cls.mode === "port_conflict") summary = "port conflict (non-Aerial process on port)";
  else if (state.installed && state.loaded) summary = "manager reports up but health failed";
  else if (state.installed) summary = "installed (not running)";
  else summary = "not installed";
  return {
    schema: "aerial.service-status.v1",
    platform: process.platform,
    supported: true,
    config: { host: config.host, port: config.port },
    service: { platform: process.platform, ...state },
    health,
    logs: logsBlock(),
    auth: authBlock(),
    summary
  };
}

export const _internal = {
  SERVICE_LABEL,
  WIN_TASK_NAME,
  plistPath,
  darwinWrapperPath,
  winWrapperPath,
  aerialLogPath,
  stdioLogPath,
  parseWrapperLogValues,
  buildSchtasksArgs,
  quoteSchtasksTR,
  classifyHealth
};
